package br.com.softplan.sienge.service;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import br.com.softplan.sienge.entity.ChargeEntity;
import br.com.softplan.sienge.entity.StreetEntity;
import br.com.softplan.sienge.entity.VehicleEntity;
import br.com.softplan.sienge.main.App;
import br.com.softplan.sienge.service.ServiceCost;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
import org.springframework.test.context.transaction.TransactionalTestExecutionListener;

import java.util.ArrayList;
import java.util.List;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = App.class)
@DataJpaTest
public class ServiceCostTest {

    @Autowired
    private ServiceCost serviceCost;



    private VehicleEntity vehicleEntity;
    private StreetEntity streetEntity;
    private ChargeEntity chargeEntity;
    private List<StreetEntity> streetEntities;


    @Before
    public void getVehicle(){
        VehicleEntity vehicleEntity = new VehicleEntity();
        vehicleEntity.setType("Caminhão baú");
        this.vehicleEntity = vehicleEntity;
    }

    @Before
    public void getStreetEntity(){
        StreetEntity streetEntity = new StreetEntity();
        streetEntity.setKilometer(100);
        streetEntity.setTypeStreet("Pavimentada");
        this.streetEntity = streetEntity;
    }

    @Before
    public void getListStrets(){
        List<StreetEntity> streetEntities = new ArrayList<>();
        streetEntities.add(streetEntity);
        this.streetEntities = streetEntities;
    }

    @Before
    public void getCharge(){
        ChargeEntity chargeEntity = new ChargeEntity();
        chargeEntity.setWeight(10);
        this.chargeEntity = chargeEntity;
    }

    @Test
    public void shouldAtributesNotNull() {
        assertNotNull(vehicleEntity);
        assertNotNull(streetEntities);
        assertNotNull(streetEntity);
        assertNotNull(chargeEntity);
        assertNotNull(serviceCost);
    }


    @Test
    public void shouldCost(){
        double mainCost = serviceCost.getMainCost(vehicleEntity, streetEntities, chargeEntity );
        assertNotNull(mainCost);

    }
}
