/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import br.com.softplan.sienge.entity.ChargeEntity;
import br.com.softplan.sienge.entity.StreetEntity;
import br.com.softplan.sienge.entity.VehicleEntity;
import br.com.softplan.sienge.main.App;
import br.com.softplan.sienge.service.ServiceCost;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {

    @Autowired
    ServiceCost serviceCost;

    private VehicleEntity vehicleEntity;
    private StreetEntity streetEntity;
    private ChargeEntity chargeEntity;
    private List<StreetEntity> streetEntities;


    @Before
    public void getVehicle(){
        VehicleEntity vehicleEntity = new VehicleEntity();
        vehicleEntity.setType("Caminhão baú");
        this.vehicleEntity = vehicleEntity;
    }

    @Before
    public void getStreetEntity(){
        StreetEntity streetEntity = new StreetEntity();
        streetEntity.setKilometer(100);
        streetEntity.setTypeStreet("Pavimentada");
        this.streetEntity = streetEntity;
    }

    @Before
    public void getListStrets(){
        List<StreetEntity> streetEntities = new ArrayList<>();
        streetEntities.add(streetEntity);
        this.streetEntities = streetEntities;
    }

    @Before
    public void getCharge(){
        ChargeEntity chargeEntity = new ChargeEntity();
        chargeEntity.setWeight(10);
        this.chargeEntity = chargeEntity;
    }

    @Test public void testAppHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());

//        double cost = serviceCost.MainCostDistance(vehicleEntity,streetEntities, chargeEntity);
//        System.out.println(cost);
    }
}
